spring:
  datasource:

    url: ${DB_URL:jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres}
    username: ${DB_USER:postgres.rpmmexmvurkkshswcmqt}
    password: ${DB_PASSWORD:your_real_supabase_password}
    driver-class-name: org.postgresql.Driver

  hikari:

    maximum-pool-size: 2
    minimum-idle: 1
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.time_zone: Asia/Kolkata

  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:admin123}
      roles: ADMIN

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${SENDGRID_FROM_EMAIL}

server:
  timezone: Asia/Kolkata
